// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Photographer struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	Specialty string    `json:"specialty"`
	City      string    `json:"city"`
	Bio       string    `json:"bio"`
	Email     string    `json:"email"`
	Whatsapp  string    `json:"whatsapp"`
	Website   string    `json:"website"`
	CreatedAt time.Time `json:"created_at"`
	AvatarUrl string    `json:"avatar_url"`
	CoverUrl  string    `json:"cover_url"`
}
