// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: photographers.sql

package db

import (
	"context"
)

const getPhotographer = `-- name: GetPhotographer :one
SELECT id, name, specialty, city, bio, email, whatsapp, website
FROM photographers
WHERE id = $1
`

type GetPhotographerRow struct {
	ID        int32  `json:"id"`
	Name      string `json:"name"`
	Specialty string `json:"specialty"`
	City      string `json:"city"`
	Bio       string `json:"bio"`
	Email     string `json:"email"`
	Whatsapp  string `json:"whatsapp"`
	Website   string `json:"website"`
}

func (q *Queries) GetPhotographer(ctx context.Context, id int32) (GetPhotographerRow, error) {
	row := q.db.QueryRowContext(ctx, getPhotographer, id)
	var i GetPhotographerRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Specialty,
		&i.City,
		&i.Bio,
		&i.Email,
		&i.Whatsapp,
		&i.Website,
	)
	return i, err
}

const insertPhotographer = `-- name: InsertPhotographer :one
INSERT INTO photographers (name, specialty, city, bio, email, whatsapp, website)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, specialty, city, bio, email, whatsapp, website, created_at
`

type InsertPhotographerParams struct {
	Name      string `json:"name"`
	Specialty string `json:"specialty"`
	City      string `json:"city"`
	Bio       string `json:"bio"`
	Email     string `json:"email"`
	Whatsapp  string `json:"whatsapp"`
	Website   string `json:"website"`
}

func (q *Queries) InsertPhotographer(ctx context.Context, arg InsertPhotographerParams) (Photographer, error) {
	row := q.db.QueryRowContext(ctx, insertPhotographer,
		arg.Name,
		arg.Specialty,
		arg.City,
		arg.Bio,
		arg.Email,
		arg.Whatsapp,
		arg.Website,
	)
	var i Photographer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Specialty,
		&i.City,
		&i.Bio,
		&i.Email,
		&i.Whatsapp,
		&i.Website,
		&i.CreatedAt,
	)
	return i, err
}

const listPhotographers = `-- name: ListPhotographers :many
SELECT id, name, specialty, city
FROM photographers
ORDER BY id
`

type ListPhotographersRow struct {
	ID        int32  `json:"id"`
	Name      string `json:"name"`
	Specialty string `json:"specialty"`
	City      string `json:"city"`
}

func (q *Queries) ListPhotographers(ctx context.Context) ([]ListPhotographersRow, error) {
	rows, err := q.db.QueryContext(ctx, listPhotographers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPhotographersRow
	for rows.Next() {
		var i ListPhotographersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Specialty,
			&i.City,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
